services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adventure_sheet_DB
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data:
